### ISSUE TITLE
Deepslate Bauxite and Deepslate Nickel both use (what is presumably) Deepslate Nickel's texture

### ISSUE THREAD

**Issue by phoenix492** [LopyLuna/Create-Unify#1]
![image](https://github.com/user-attachments/assets/9fa6983f-4394-48e4-85d2-f50ca3cc261d)

**Comment by LopyLuna** [comment]
yep not intentional and use the same nickel texture by accident

**Comment by LopyLuna** [comment]
fixed and update soon
