### ISSUE TITLE
Exception in thread "main" java.lang.ClassCastException: Cannot cast net.minecraftforge.fml.loading.moddiscovery.AbstractModProvider$DefaultModFileInfo to net.minecraftforge.fml.loading.moddiscovery.ModFileInfo

### ISSUE THREAD

**Issue by xg787** [LopyLuna/Create-Unify#3]
[latest.log](https://github.com/user-attachments/files/17104374/latest.log)

**Comment by LopyLuna** [comment]
that doesnt give any good info

**Comment by LopyLuna** [comment]
try updating mods and modloader since its not pointing anywhere about unify

**Comment by xg787** [comment]
i am on the latest version of forge and the issue only starts when unify is updated to the release version

**Comment by LopyLuna** [comment]
could you provide more info please

**Comment by xg787** [comment]
unfortunately i cant give anything more other than the mod list as the game refuses to load past that point with the latest version of the mod

[modlist.txt](https://github.com/user-attachments/files/17110993/modlist.txt)

**Comment by LopyLuna** [comment]
try it with unify only first and if it works then its a conflict with a mod and you gotta find the conflicted mod
